### ISSUE TITLE
AsyncClient::add() never returns

### ISSUE THREAD

**Issue by drejkus** [me-no-dev/AsyncTCP#4]
Hi,
I have issue with `AsyncClient::add()` - it never returns, when adding only 2 bytes. 
I'm actually trying to modify https://github.com/marvinroger/async-mqtt-client to work with ESP32, but it fails right at the beginning in the `onConnect` callback where it tries to assemeble the packet. 

Please do you have any clue what goes wrong or where to look?

**Comment by me-no-dev** [comment]
Hmm... that is rather strange... need to investigate

**Comment by drejkus** [comment]
Just adding simple test file. 

[AsyncTest.zip](https://github.com/me-no-dev/AsyncTCP/files/1375730/AsyncTest.zip)

**Comment by copercini** [comment]
I'm hitting the exactly same issue, one of the problems is in dns resolution, AsyncMqttClient doesn't have a `dns_found_callback` function to continue after AsyncTCP return an IP here: https://github.com/me-no-dev/AsyncTCP/blob/master/src/AsyncTCP.cpp#L555

with IP directly, [seems to be something between _tcp_write and _tcp_write_api](https://github.com/me-no-dev/AsyncTCP/blob/master/src/AsyncTCP.cpp#L245) because none of my debug messages in `_tcp_write_api` are printed, and the last one is in `_tcp_write`

**Comment by me-no-dev** [comment]
Aaaahhhh... onConnect runs on the network thread... let me try to figure this out...

**Comment by me-no-dev** [comment]
guys try the latest commit :)

**Comment by drejkus** [comment]
Brilliant! Works for me. 

@copercini - I hit the DNS issue aswell, but I belive that the problem is in AsyncMqttClient where it does not return AsyncTCP `connect()` result in it's own [`connect()`](https://github.com/marvinroger/async-mqtt-client/blob/ddbf4d13287f72bbd281b463f5f032cfe035869f/src/AsyncMqttClient.cpp#L677). If it did we could simply issue a reconnect. But that is another story

**Comment by me-no-dev** [comment]
dns issue should also be fixed ;)

**Comment by copercini** [comment]
Awesome man!!!

Both problems was solved here, thanks!

**Comment by me-no-dev** [comment]
:) closing then :P
